CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(300) NOT NULL,
    login varchar(100) NOT NULL,
    user_name varchar(100) NOT NULL,
    birthday date
);

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id INTEGER PRIMARY KEY,
    mpa_name varchar(10) UNIQUE NOT NULL,
    description varchar(200)
);

CREATE TABLE IF NOT EXISTS films
(
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name varchar(100) NOT NULL,
    description varchar(200),
    release_date date,
    duration bigint,
    rate integer,
    mpa_id integer REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS genres
(
    genre_id INTEGER PRIMARY KEY,
    genre_name varchar(15) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id bigint NOT NULL REFERENCES films (film_id),
    genre_id integer NOT NULL REFERENCES genres (genre_id),
    CONSTRAINT film_genre_pk PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id bigint NOT NULL REFERENCES users (user_id),
    film_id bigint NOT NULL REFERENCES films (film_id),
    CONSTRAINT favorite_user_film_pk PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id bigint NOT NULL REFERENCES users (user_id),
    friend_id bigint NOT NULL REFERENCES users (user_id),
    friend_status varchar(10) NOT NULL,
    CONSTRAINT user_friend_pk PRIMARY KEY (user_id, friend_id)
);