--liquibase formatted sql
--changeset filmorate_sql:initial_base

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(300) NOT NULL,
    login varchar(100) NOT NULL,
    name varchar(100) NOT NULL,
    birthday date
);

CREATE TABLE IF NOT EXISTS mpa
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(10) UNIQUE NOT NULL,
    description varchar(200)
);

CREATE TABLE IF NOT EXISTS films
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    description varchar(200),
    release_date date,
    duration bigint,
    rate integer,
    mpa integer REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS genres
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(15) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id bigint NOT NULL REFERENCES films (id),
    genre_id integer NOT NULL REFERENCES genres (id),
    CONSTRAINT film_genre PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id bigint NOT NULL REFERENCES users (id),
    film_id bigint NOT NULL REFERENCES films (id),
    CONSTRAINT favorite_user_film PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id bigint NOT NULL REFERENCES users (id),
    friend_id bigint NOT NULL REFERENCES users (id),
    friend_status varchar(10) NOT NULL,
    CONSTRAINT user_friend PRIMARY KEY (user_id, friend_id)
);